version: "3.8"
services:
  service1:
    build: ./service1
    image: trizmanz/service1:latest 
    container_name: service1       
    ports:
    - target: 5000
      published: 80
    environment:
      DATABASE_URI: ${DATABASE_URI}
      
  service2:
    build: ./service2
    image: trizmanz/service2:latest 
    container_name: number_api 

  service3:
    build: ./service3
    image: trizmanz/service3:latest 
    container_name: day_api  
  
  service4:
    build: ./service4
    image: trizmanz/service4:latest 
    container_name: fortune_api 
