version: "3.7"
services:
  service1:
    build: ./service1
    image: trizmanz/service1:latest 
    container_name: service1       
    ports:
    - target: 5000
      published: 80
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 4  
      
  service2:
    build: ./service2
    image: trizmanz/service2:latest 
    container_name: service2  
    deploy:  
      replicas: 4

  service3:
    build: ./service3
    image: trizmanz/service3:latest 
    container_name: service3  
    deploy:
      replicas: 4  
      
  service4:
    build: ./service4
    image: trizmanz/service4:latest 
    container_name: service4 
    deploy:
      replicas: 4
