---
# tasks file for docker
# it has all the instruction we need to have docker installed. This will installed docker for us
- name: Install APT requirements
  apt:
    state: latest
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip
    - python3
  # Add Docker's official GPG key (authentication)  
- name: Add Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  # Location where Docker stuff is installed from
- name: Add Docker APT Repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
    state: present
  # Installation process for Docker
- name: Install Docker with APT
  apt:
    state: latest
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  # Ansible is a python app and it needs python pips installed too
- name: pip docker
  pip:
    executable: pip3
    name: docker
  ## we want the swarm to be controlled by the jenkins' user so jenkins vm has a user to ssh into the swarm manager vm with Docker priviledges
- name: Add a jenkins user 
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes